/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Empleado;

/**
 *
 * @author TOR
 */
public class InternalFrame_NuevoEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrame_nuevoUsuario
     */
    public InternalFrame_NuevoEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_backgrounf = new javax.swing.JPanel();
        panel_datos_Usuario = new javax.swing.JPanel();
        Label_nombreCliente = new javax.swing.JLabel();
        label_apellidoCliente = new javax.swing.JLabel();
        label_documentoIdentidadCliente = new javax.swing.JLabel();
        label_correoCliente = new javax.swing.JLabel();
        label_contraseñaCliente = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_documentoIdentificacion = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        label_telefonoCliente = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        label_apellidoCliente1 = new javax.swing.JLabel();
        txt_idEmpleado = new javax.swing.JTextField();
        label_apellidoCliente2 = new javax.swing.JLabel();
        txt_idUsuario = new javax.swing.JTextField();
        botton_guardarDatosCliente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Nuevo Empleado");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_backgrounf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_datos_Usuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        Label_nombreCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Label_nombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label_nombreCliente.setText("Nombre");

        label_apellidoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_apellidoCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_apellidoCliente.setText("Apellido");

        label_documentoIdentidadCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_documentoIdentidadCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_documentoIdentidadCliente.setText("Documento Identidad");

        label_correoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_correoCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_correoCliente.setText("Correo");

        label_contraseñaCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_contraseñaCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_contraseñaCliente.setText("Dirección");

        txt_nombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_apellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_documentoIdentificacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_correo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_direccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        label_telefonoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_telefonoCliente.setText("Teléfono");

        label_apellidoCliente1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_apellidoCliente1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_apellidoCliente1.setText("ID Empleado");

        txt_idEmpleado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        label_apellidoCliente2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_apellidoCliente2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_apellidoCliente2.setText("ID Usuario");

        txt_idUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        javax.swing.GroupLayout panel_datos_UsuarioLayout = new javax.swing.GroupLayout(panel_datos_Usuario);
        panel_datos_Usuario.setLayout(panel_datos_UsuarioLayout);
        panel_datos_UsuarioLayout.setHorizontalGroup(
            panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_correoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_documentoIdentidadCliente)
                    .addComponent(label_telefonoCliente)
                    .addComponent(label_apellidoCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_apellidoCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_contraseñaCliente))
                .addGap(72, 72, 72)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addComponent(txt_apellido)
                        .addComponent(txt_documentoIdentificacion)
                        .addComponent(txt_correo)
                        .addComponent(txt_telefono)
                        .addComponent(txt_idEmpleado)
                        .addComponent(txt_idUsuario)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        panel_datos_UsuarioLayout.setVerticalGroup(
            panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_apellidoCliente1)
                    .addComponent(txt_idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_nombreCliente)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_apellidoCliente2)
                    .addComponent(txt_idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_apellidoCliente))
                .addGap(18, 18, 18)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_documentoIdentidadCliente)
                    .addComponent(txt_documentoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_correoCliente)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_contraseñaCliente)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_telefonoCliente)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        panel_backgrounf.add(panel_datos_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 380));

        getContentPane().add(panel_backgrounf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 410));

        botton_guardarDatosCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        botton_guardarDatosCliente.setText("Guardar");
        botton_guardarDatosCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botton_guardarDatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_guardarDatosClienteActionPerformed(evt);
            }
        });
        getContentPane().add(botton_guardarDatosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botton_guardarDatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_guardarDatosClienteActionPerformed
        Empleado nempleado = new Empleado();

        if (txt_idEmpleado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Porfavor ingrese un valor en tosos los campos");
        } else {

                nempleado.setIdEmpleado(Integer.parseInt(txt_idEmpleado.getText().trim()));
                nempleado.setNombre(txt_nombre.getText().trim());
                nempleado.setApellido(txt_apellido.getText().trim());
                nempleado.setDireccion(txt_direccion.getText().trim());
                nempleado.setDocumento(txt_documentoIdentificacion.getText().trim());
                nempleado.setCorreo(txt_correo.getText().trim());
                nempleado.setTelefono(txt_telefono.getText().trim());
                nempleado.setIdUsuario(Integer.parseInt(txt_idUsuario.getText().trim()));

                    JOptionPane.showMessageDialog(null, "Creacion de Cliente Exitosa");

                


        }

        //Limpiar campos
        txt_idEmpleado.setText("");
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_direccion.setText("");
        txt_documentoIdentificacion.setText("");
        txt_correo.setText("");
        txt_telefono.setText("");
        txt_idUsuario.setText("");
    }//GEN-LAST:event_botton_guardarDatosClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_nombreCliente;
    private javax.swing.JButton botton_guardarDatosCliente;
    private javax.swing.JLabel label_apellidoCliente;
    private javax.swing.JLabel label_apellidoCliente1;
    private javax.swing.JLabel label_apellidoCliente2;
    private javax.swing.JLabel label_contraseñaCliente;
    private javax.swing.JLabel label_correoCliente;
    private javax.swing.JLabel label_documentoIdentidadCliente;
    private javax.swing.JLabel label_telefonoCliente;
    private javax.swing.JPanel panel_backgrounf;
    private javax.swing.JPanel panel_datos_Usuario;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_documentoIdentificacion;
    private javax.swing.JTextField txt_idEmpleado;
    private javax.swing.JTextField txt_idUsuario;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
