/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.Ctrl_Cliente;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;

import static vista.InternalFrame_GestionarCliente.tabel_GestionClientes;

/**
 *
 * @author TOR
 */
public class InternalFrame_GestionarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrame_GestionarUsuarios
     */
    private int idCliente;

    public InternalFrame_GestionarCliente() {
        initComponents();
        this.cargartablaClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondoGestionarUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_GestionClientes = new javax.swing.JTable();
        panelGestionUsuario = new javax.swing.JPanel();
        mostrar_mostrarDatos = new javax.swing.JPanel();
        label_nombreCliente = new javax.swing.JLabel();
        label_apellidoCliente = new javax.swing.JLabel();
        txt_idCliente = new javax.swing.JTextField();
        txt_apellido_Cliente = new javax.swing.JTextField();
        label_documentoIdentidadCliente = new javax.swing.JLabel();
        label_correoCliente = new javax.swing.JLabel();
        txt_documentoIdentidad_Cliente = new javax.swing.JTextField();
        txt_correo_Cliente = new javax.swing.JTextField();
        label_dirreción = new javax.swing.JLabel();
        txt_dirrecion_Cliente = new javax.swing.JTextField();
        label_nombreCliente1 = new javax.swing.JLabel();
        txt_telefonoCliente = new javax.swing.JTextField();
        label_nombreCliente2 = new javax.swing.JLabel();
        txt_nombre_Cliente = new javax.swing.JTextField();
        botton_eliminarCliente = new javax.swing.JButton();
        botton_actualizar_datosCliente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gestionar Clientes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_fondoGestionarUsuarios.setBackground(java.awt.Color.white);
        panel_fondoGestionarUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_GestionClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabel_GestionClientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tabel_GestionClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Cliente", "Nombre", "Apellido", "Documento Identidad", "correo", "Dirreción", "Teléfono"
            }
        ));
        jScrollPane1.setViewportView(tabel_GestionClientes);

        panel_fondoGestionarUsuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 880, 160));

        panelGestionUsuario.setBackground(new java.awt.Color(255, 255, 255));
        panelGestionUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_fondoGestionarUsuarios.add(panelGestionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 890, 80));

        mostrar_mostrarDatos.setBackground(new java.awt.Color(255, 255, 255));

        label_nombreCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_nombreCliente.setText("ID Nombre");

        label_apellidoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_apellidoCliente.setText("Apellido");

        label_documentoIdentidadCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_documentoIdentidadCliente.setText("Documento ");

        label_correoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_correoCliente.setText("Correo");

        txt_documentoIdentidad_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_documentoIdentidad_ClienteActionPerformed(evt);
            }
        });

        label_dirreción.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_dirreción.setText("Dirección");

        label_nombreCliente1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_nombreCliente1.setText("Teléfono");

        txt_telefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoClienteActionPerformed(evt);
            }
        });

        label_nombreCliente2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_nombreCliente2.setText("Nombre");

        botton_eliminarCliente.setText("Eliminar");
        botton_eliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_eliminarClienteActionPerformed(evt);
            }
        });

        botton_actualizar_datosCliente.setText("Actualizar");
        botton_actualizar_datosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_actualizar_datosClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mostrar_mostrarDatosLayout = new javax.swing.GroupLayout(mostrar_mostrarDatos);
        mostrar_mostrarDatos.setLayout(mostrar_mostrarDatosLayout);
        mostrar_mostrarDatosLayout.setHorizontalGroup(
            mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrar_mostrarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mostrar_mostrarDatosLayout.createSequentialGroup()
                        .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nombreCliente)
                            .addComponent(label_documentoIdentidadCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_documentoIdentidad_Cliente)
                            .addComponent(txt_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mostrar_mostrarDatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label_nombreCliente1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nombreCliente2)
                    .addComponent(label_correoCliente))
                .addGap(18, 18, 18)
                .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mostrar_mostrarDatosLayout.createSequentialGroup()
                        .addComponent(txt_nombre_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_apellidoCliente)
                        .addGap(18, 18, 18)
                        .addComponent(txt_apellido_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mostrar_mostrarDatosLayout.createSequentialGroup()
                        .addComponent(txt_correo_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_dirreción)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_dirrecion_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(290, 290, 290))
            .addGroup(mostrar_mostrarDatosLayout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(botton_actualizar_datosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botton_eliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mostrar_mostrarDatosLayout.setVerticalGroup(
            mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrar_mostrarDatosLayout.createSequentialGroup()
                .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nombreCliente2)
                    .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nombre_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_apellidoCliente)
                        .addComponent(txt_apellido_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_nombreCliente)
                        .addComponent(txt_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_correoCliente)
                    .addComponent(txt_correo_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_dirreción)
                    .addComponent(txt_dirrecion_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_documentoIdentidadCliente)
                    .addComponent(txt_documentoIdentidad_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nombreCliente1)
                    .addComponent(txt_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botton_actualizar_datosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botton_eliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        panel_fondoGestionarUsuarios.add(mostrar_mostrarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 910, 290));

        getContentPane().add(panel_fondoGestionarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botton_actualizar_datosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_actualizar_datosClienteActionPerformed
        if (!txt_idCliente.getText().isEmpty()) {
            Cliente cliente = new Cliente();
            Ctrl_Cliente controcliente = new Ctrl_Cliente();

            cliente.setIdCliente(Integer.parseInt(txt_idCliente.getText().trim()));
            cliente.setNombre(txt_nombre_Cliente.getText().trim());
            cliente.setApellido(txt_apellido_Cliente.getText().trim());
            cliente.setDocumento(txt_documentoIdentidad_Cliente.getText().trim());
            cliente.setCorreo(txt_correo_Cliente.getText().trim());
            cliente.setTelefono(txt_telefonoCliente.getText().trim());
            cliente.setDireccion(txt_dirrecion_Cliente.getText().trim());
            if (controcliente.actualizar(cliente, idCliente)) {
                JOptionPane.showMessageDialog(null, "Cliente modificado con éxito");
                txt_idCliente.setText("");
                txt_nombre_Cliente.setText("");
                txt_apellido_Cliente.setText("");
                txt_dirrecion_Cliente.setText("");
                txt_documentoIdentidad_Cliente.setText("");
                txt_correo_Cliente.setText("");
                txt_telefonoCliente.setText("");
                cargartablaClientes();
            } else {
                JOptionPane.showMessageDialog(null, "El Cliente no se actualizó");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una cliente");
        }
    }//GEN-LAST:event_botton_actualizar_datosClienteActionPerformed

    private void txt_documentoIdentidad_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_documentoIdentidad_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_documentoIdentidad_ClienteActionPerformed

    private void txt_telefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoClienteActionPerformed

    private void botton_eliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_eliminarClienteActionPerformed
        if (!txt_idCliente.getText().isEmpty()) {
            Cliente cliente = new Cliente();
            Ctrl_Cliente controcliente = new Ctrl_Cliente();
            
            cliente.setIdCliente(Integer.parseInt(txt_idCliente.getText().trim()));
            cliente.setNombre(txt_nombre_Cliente.getText().trim());
            cliente.setApellido(txt_apellido_Cliente.getText().trim());
            cliente.setDocumento(txt_documentoIdentidad_Cliente.getText().trim());
            cliente.setCorreo(txt_correo_Cliente.getText().trim());
            cliente.setTelefono(txt_telefonoCliente.getText().trim());
            cliente.setDireccion(txt_dirrecion_Cliente.getText().trim());
            if (controcliente.eliminar(cliente.getIdCliente())) {
                JOptionPane.showMessageDialog(null, "Línea eliminada correctamente");
                txt_idCliente.setText("");
                txt_nombre_Cliente.setText("");
                txt_apellido_Cliente.setText("");
                txt_dirrecion_Cliente.setText("");
                txt_documentoIdentidad_Cliente.setText("");
                txt_correo_Cliente.setText("");
                txt_telefonoCliente.setText("");
                cargartablaClientes();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una cliente");
        }
    }//GEN-LAST:event_botton_eliminarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botton_actualizar_datosCliente;
    private javax.swing.JButton botton_eliminarCliente;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_apellidoCliente;
    private javax.swing.JLabel label_correoCliente;
    private javax.swing.JLabel label_dirreción;
    private javax.swing.JLabel label_documentoIdentidadCliente;
    private javax.swing.JLabel label_nombreCliente;
    private javax.swing.JLabel label_nombreCliente1;
    private javax.swing.JLabel label_nombreCliente2;
    private javax.swing.JPanel mostrar_mostrarDatos;
    private javax.swing.JPanel panelGestionUsuario;
    private javax.swing.JPanel panel_fondoGestionarUsuarios;
    public static javax.swing.JTable tabel_GestionClientes;
    private javax.swing.JTextField txt_apellido_Cliente;
    private javax.swing.JTextField txt_correo_Cliente;
    private javax.swing.JTextField txt_dirrecion_Cliente;
    private javax.swing.JTextField txt_documentoIdentidad_Cliente;
    private javax.swing.JTextField txt_idCliente;
    private javax.swing.JTextField txt_nombre_Cliente;
    private javax.swing.JTextField txt_telefonoCliente;
    // End of variables declaration//GEN-END:variables

// metodo para mostrar todas las clientes
    private void cargartablaClientes() {
        Connection cn = conexion.Conexion.conectar();

        DefaultTableModel model = new DefaultTableModel();
        String sql = "SELECT * FROM cliente;";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            InternalFrame_GestionarCliente.tabel_GestionClientes = new JTable(model);
            InternalFrame_GestionarCliente.jScrollPane1.setViewportView(InternalFrame_GestionarCliente.tabel_GestionClientes);

            model.addColumn("Id_Cliente");
            model.addColumn("Nombre");
            model.addColumn("Apellido");
            model.addColumn("Documento");
            model.addColumn("Correo");
            model.addColumn("Direccion");
            model.addColumn("Telefono");

            while (rs.next()) {

                Object fila[] = new Object[7];

                for (int i = 0; i < 7; i++) {
                    fila[i] = rs.getObject(i + 1);

                }
                model.addRow(fila);

            }
            cn.close();

        } catch (SQLException e) {

            System.out.println("Error al llenar la tabla Cliente" + e);
        }

        tabel_GestionClientes.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = tabel_GestionClientes.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idCliente = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosLineaSeleccionada(idCliente);
                }
            }
        });

    }

    private void EnviarDatosLineaSeleccionada(int idCliente) {
        try {
            Connection cno = conexion.Conexion.conectar();
            PreparedStatement pst = cno.prepareStatement("SELECT * FROM cliente WHERE id_cliente = '" + idCliente + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                txt_idCliente.setText(rs.getString("Id_Cliente"));
                txt_nombre_Cliente.setText(rs.getString("Nombre"));
                txt_apellido_Cliente.setText(rs.getString("Apellido"));
                txt_documentoIdentidad_Cliente.setText(rs.getString("Documento"));
                txt_correo_Cliente.setText(rs.getString("Correo"));
                txt_dirrecion_Cliente.setText(rs.getString("Direccion"));
                txt_telefonoCliente.setText(rs.getString("Telefono"));

            }
            cno.close();

        } catch (SQLException e) {

            System.err.println("Error cargar categoria" + e);
        }
    }

}
