/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;


import controlador.Ctrl_Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author TOR
 */
public class InternalFrame_NuevoUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrame_nuevoUsuario
     */
    public InternalFrame_NuevoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_backgrounf = new javax.swing.JPanel();
        panel_datos_Usuario = new javax.swing.JPanel();
        Label_nombreUsuario = new javax.swing.JLabel();
        label_apellidoUsuario = new javax.swing.JLabel();
        seleccionCargo = new javax.swing.JComboBox<>();
        label_rolUsuario = new javax.swing.JLabel();
        txt_idusuario = new javax.swing.JTextField();
        txt_contraseñaUsuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Nuevo Usuario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_backgrounf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_nombreUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Label_nombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label_nombreUsuario.setText("ID Usuario");

        label_apellidoUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_apellidoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_apellidoUsuario.setText("Contraseña");

        seleccionCargo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        seleccionCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", " " }));
        seleccionCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seleccionCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionCargoActionPerformed(evt);
            }
        });

        label_rolUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_rolUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_rolUsuario.setText("Cargo");

        txt_idusuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_contraseñaUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_datos_UsuarioLayout = new javax.swing.GroupLayout(panel_datos_Usuario);
        panel_datos_Usuario.setLayout(panel_datos_UsuarioLayout);
        panel_datos_UsuarioLayout.setHorizontalGroup(
            panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_apellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_rolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_idusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addComponent(txt_contraseñaUsuario))
                    .addComponent(seleccionCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );
        panel_datos_UsuarioLayout.setVerticalGroup(
            panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_nombreUsuario)
                    .addComponent(txt_idusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_apellidoUsuario)
                    .addComponent(txt_contraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_rolUsuario)
                    .addComponent(seleccionCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        panel_backgrounf.add(panel_datos_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 360));

        getContentPane().add(panel_backgrounf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Usuario nusuario = new Usuario();
        Ctrl_Usuario controlusuario = new Ctrl_Usuario(); 

        if (txt_idusuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Porfavor ingrese un valor en toos los campos");
        } else {

            try {
                if (!controlusuario.Existeidusuario(Integer.parseInt(txt_idusuario.getText().trim()))) {
                    nusuario.setIdUsuario(Integer.parseInt(txt_idusuario.getText().trim()));
                    nusuario.setPassword(txt_contraseñaUsuario.getText().trim());
                    nusuario.setIdcargo(Integer.parseInt(seleccionCargo.getSelectedItem().toString()));

                    if (controlusuario.guardarusuario(nusuario)) {
                        JOptionPane.showMessageDialog(null, "Creacion de Linea Exitosa");

                    } else {
                        JOptionPane.showMessageDialog(null, "Error al guardar");

                    }

                } else {
                    JOptionPane.showMessageDialog(null, "La categoria o id_Linea ya existe ");

                }
            } catch (SQLException ex) {
              
            }

        }

        //Limpiar campos
        txt_idusuario.setText("");
        txt_contraseñaUsuario.setText("");
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void seleccionCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionCargoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_nombreUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel label_apellidoUsuario;
    private javax.swing.JLabel label_rolUsuario;
    private javax.swing.JPanel panel_backgrounf;
    private javax.swing.JPanel panel_datos_Usuario;
    private javax.swing.JComboBox<String> seleccionCargo;
    private javax.swing.JTextField txt_contraseñaUsuario;
    private javax.swing.JTextField txt_idusuario;
    // End of variables declaration//GEN-END:variables
}
