/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Localidad;

/**
 *
 * @author andre
 */
public class AgregarLocalidadDialog extends javax.swing.JDialog {

    /**
     * Creates new form AgregarLocalidadDialog
     */
    public AgregarLocalidadDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        TextPrompt phn = new TextPrompt("Nombre de la Localidad",txtNombreLocalidad); 
        TextPrompt phd = new TextPrompt("Lugares disponibles en la Localidad",txtEspaciosDisponibles); 
        TextPrompt phfe = new TextPrompt("Precio de la Localidad",jTextField3); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreLocalidad = new javax.swing.JTextField();
        txtEspaciosDisponibles = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        btonAgregarLocalidadDialog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNombreLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreLocalidadActionPerformed(evt);
            }
        });

        txtEspaciosDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspaciosDisponiblesActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        btonAgregarLocalidadDialog.setText("Agregar");
        btonAgregarLocalidadDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonAgregarLocalidadDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(txtEspaciosDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(txtNombreLocalidad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btonAgregarLocalidadDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtNombreLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEspaciosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btonAgregarLocalidadDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEspaciosDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspaciosDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspaciosDisponiblesActionPerformed

    private void txtNombreLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreLocalidadActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btonAgregarLocalidadDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonAgregarLocalidadDialogActionPerformed
        // Obtener los valores ingresados por el usuario
        String nombreLocalidad = txtNombreLocalidad.getText().trim();
        int capacidad = Integer.parseInt(txtEspaciosDisponibles.getText().trim());
        float precio = Float.parseFloat(jTextField3.getText().trim());

        // Validar los valores ingresados
        if (nombreLocalidad.isEmpty() || capacidad <= 0 || precio <= 0) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos correctamente.");
            return;
        }

        // Crear una instancia de la clase Localidad con los valores ingresados por el usuario
        Localidad localidad = new Localidad();
        localidad.setTipoLocalidad(nombreLocalidad);
        localidad.setEspaciosDisponibles(capacidad);
        localidad.setPrecio(precio);

        // Cerrar el diálogo y devolver el control al formulario principal
        this.dispose();
    }//GEN-LAST:event_btonAgregarLocalidadDialogActionPerformed
    public String getNombreLocalidad() {
        return txtNombreLocalidad.getText().trim();
    }

    public int getCapacidad() {
        try {
            return Integer.parseInt(txtEspaciosDisponibles.getText().trim());
        } catch (NumberFormatException e) {
            return -1; // Devuelve -1 si no se puede convertir a entero
        }
    }

    public float getPrecio() {
        try {
            return Float.parseFloat(jTextField3.getText().trim());
        } catch (NumberFormatException e) {
            return -1; // Devuelve -1 si no se puede convertir a flotante
        }
    }

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btonAgregarLocalidadDialog;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtEspaciosDisponibles;
    private javax.swing.JTextField txtNombreLocalidad;
    // End of variables declaration//GEN-END:variables
}
