/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JDesktopPane;

/**
 *
 * @author TOR
 */
public class view_Menu extends javax.swing.JFrame {

    public static JDesktopPane jDesktopPane_menu;

    public view_Menu() {
        initComponents();

        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_usuario = new javax.swing.JMenu();
        menuItem_nuevo_Usuario = new javax.swing.JMenuItem();
        menuItem_Gestionar_Usuarios = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        menu_factura = new javax.swing.JMenu();
        jMenuItem_nueva_venta = new javax.swing.JMenuItem();
        jMenuItem_gestionar_venta = new javax.swing.JMenuItem();
        menu_cerrarSesion = new javax.swing.JMenu();
        menuItem_cerrar_sesion = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");
        setMinimumSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 0, -1, 283));

        jMenuBar1.setBorder(null);
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        menu_usuario.setBorder(null);
        menu_usuario.setText("Admins");
        menu_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_usuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        menu_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_usuario.setMinimumSize(new java.awt.Dimension(130, 50));
        menu_usuario.setPreferredSize(new java.awt.Dimension(150, 50));

        menuItem_nuevo_Usuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        menuItem_nuevo_Usuario.setText("Nuevo Usuario");
        menuItem_nuevo_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItem_nuevo_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuItem_nuevo_Usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuItem_nuevo_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_nuevo_UsuarioActionPerformed(evt);
            }
        });
        menu_usuario.add(menuItem_nuevo_Usuario);

        menuItem_Gestionar_Usuarios.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        menuItem_Gestionar_Usuarios.setText("Gestionar Usuarios");
        menuItem_Gestionar_Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItem_Gestionar_Usuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuItem_Gestionar_Usuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuItem_Gestionar_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_Gestionar_UsuariosActionPerformed(evt);
            }
        });
        menu_usuario.add(menuItem_Gestionar_Usuarios);

        jMenuBar1.add(menu_usuario);

        jMenu5.setText("Usuarios");
        jMenu5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jMenuItem7.setText("Nuevo Empleado");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("Gestionar Empleado");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        menu_factura.setBorder(null);
        menu_factura.setText("Factura");
        menu_factura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_factura.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        menu_factura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_factura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_factura.setMaximumSize(new java.awt.Dimension(120, 32767));
        menu_factura.setPreferredSize(new java.awt.Dimension(150, 40));

        jMenuItem_nueva_venta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMenuItem_nueva_venta.setText("Nueva Venta");
        jMenuItem_nueva_venta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_nueva_venta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_factura.add(jMenuItem_nueva_venta);

        jMenuItem_gestionar_venta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMenuItem_gestionar_venta.setText("Gestionar Venta");
        jMenuItem_gestionar_venta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_gestionar_venta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_gestionar_venta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_gestionar_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionar_ventaActionPerformed(evt);
            }
        });
        menu_factura.add(jMenuItem_gestionar_venta);

        jMenuBar1.add(menu_factura);

        menu_cerrarSesion.setBorder(null);
        menu_cerrarSesion.setText("Cerrar Sesión");
        menu_cerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_cerrarSesion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        menu_cerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_cerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_cerrarSesion.setPreferredSize(new java.awt.Dimension(150, 50));

        menuItem_cerrar_sesion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        menuItem_cerrar_sesion.setText("Cerrar Sesión");
        menuItem_cerrar_sesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuItem_cerrar_sesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuItem_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_cerrar_sesionActionPerformed(evt);
            }
        });
        menu_cerrarSesion.add(menuItem_cerrar_sesion);

        jMenuBar1.add(menu_cerrarSesion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_cerrar_sesionActionPerformed
        Login ventananuevalinea = new Login();
        ventananuevalinea.setVisible(true);
        dispose();

    }//GEN-LAST:event_menuItem_cerrar_sesionActionPerformed

    private void jMenuItem_gestionar_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionar_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_gestionar_ventaActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        InternalFrame_GestionarEmpleado ventananuevalinea = new InternalFrame_GestionarEmpleado();
        jDesktopPane_menu.add(ventananuevalinea);
        ventananuevalinea.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        InternalFrame_NuevoEmpleado ventananuevalinea = new InternalFrame_NuevoEmpleado();
        jDesktopPane_menu.add(ventananuevalinea);
        ventananuevalinea.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void menuItem_Gestionar_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_Gestionar_UsuariosActionPerformed
        InternalFrame_GestionarUsuarios ventanagestionusuarios = new InternalFrame_GestionarUsuarios();
        jDesktopPane_menu.add(ventanagestionusuarios);
        ventanagestionusuarios.setVisible(true);
    }//GEN-LAST:event_menuItem_Gestionar_UsuariosActionPerformed

    private void menuItem_nuevo_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_nuevo_UsuarioActionPerformed
        InternalFrame_NuevoUsuario ventananuevousuario = new InternalFrame_NuevoUsuario();
        jDesktopPane_menu.add(ventananuevousuario);
        ventananuevousuario.setVisible(true);
    }//GEN-LAST:event_menuItem_nuevo_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem_gestionar_venta;
    private javax.swing.JMenuItem jMenuItem_nueva_venta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuItem_Gestionar_Usuarios;
    private javax.swing.JMenuItem menuItem_cerrar_sesion;
    private javax.swing.JMenuItem menuItem_nuevo_Usuario;
    private javax.swing.JMenu menu_cerrarSesion;
    private javax.swing.JMenu menu_factura;
    private javax.swing.JMenu menu_usuario;
    // End of variables declaration//GEN-END:variables
}
